#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 4096 # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written

python train-faster-mots.py

python train-kitti-mots.py

python train-retina-mots.py

python train-retina_kitti-mots.py
